name: Robot Test and Publish

on:
  push:
    branches: [main]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Robot Framework
        run: pip install robotframework

      - name: Run Robot Tests
        run: |
          mkdir -p results
          robot --outputdir results tests/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./results
          publish_branch: gh-pages
